Minimizer: MINUIT # CERES 
MINUIT:
  Commands: | 
    call fcn 1
    set str 2

Parameters:
  Ag   :  DEPENDENT
  Adbar   : [ 0.3278845583329005, 0. ]
  Agp   : [ -0.229242, 0. ]
  Bdbar   : [ 0.106455, 0. ]
  Bdv   : [ 2.257300, 0. ]
  Cgp   : [ 25.0, 0. ]
  Auv  :  DEPENDENT
  Bg   : [ 0.220476, 0. ]
  Bgp   : [ -0.579452, 0. ]
  Duv  : [    0     ]
  Buv   : [ 0.922794, 0. ]
  Adv  :  DEPENDENT
  Cdbar   : [ -11.745374, 0. ]
  Cdv   : [ 13.692945, 0. ]
  Aubar: [ 0.0, 0.0 ]
  Bubar: [ 0.0, 0.0  ]
  Cg   : [ 22.652310, 0. ]
  Cubar   : [ -13.118579, 0. ]
  Cuv   : [ 2.520658, 0. ]
  Dubar   : [ -5.894220, 0. ]
  Euv   : [ -11.696922, 0. ]

  ZERO : [ 0. ]
  fs   :   [ 0.4, 0.0 ]
Parameterisations:
  par_uv:
    class: HERAPDF
    parameters: [Auv,Buv,Cuv,Duv,Euv]
  par_dv:
    class: HERAPDF
    parameters: [Adv,Bdv,Cdv]
  par_ubar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cubar,Dubar]
  par_dbar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cdbar]
  par_s:
    class: Expression
    expression: "Adbar*fs/(1-fs)*(x^Bdbar*(1-x)^Cdbar)"

  par_g:
    class: NegativeGluon
    parameters: [Ag,Bg,Cg,ZERO,ZERO,Agp,Bgp,Cgp]


DefaultDecomposition: proton
Decompositions:
  proton:
    class: UvDvUbarDbarS
    xuv: par_uv
    xdv: par_dv
    xubar: par_ubar
    xdbar: par_dbar
    xs: par_s
    xg: par_g

DefaultEvolution: proton-QCDNUM


Evolutions:
  proton-QCDNUM:
    ? !include evolutions/QCDNUM.yaml
    decomposition: proton
  antiproton:
    class: FlipCharge
  neutron:
    class: FlipUD
Q0 : 1.378404875209

? !include constants.yaml

alphas : 0.118

byReaction:

  RT_DISNC:
    ? !include reactions/RT_DISNC.yaml
  FONLL_DISNC:
    ? !include reactions/FONLL_DISNC.yaml
  FONLL_DISCC:
    ? !include reactions/FONLL_DISCC.yaml
  FFABM_DISNC:
    ? !include reactions/FFABM_DISNC.yaml
  FFABM_DISCC:
    ? !include reactions/FFABM_DISCC.yaml
  APPLgrid:
    ? !include reactions/APPLgrid.yaml
  Fractal_DISNC:
    ? !include reactions/Fractal_DISNC.yaml


hf_scheme_DISNC :
  defaultValue : 'RT_DISNC' 

hf_scheme_DISCC :
  defaultValue : 'BaseDISCC' 

