Minimizer: MINUIT # CERES 
MINUIT:
  Commands: | 
    set str 2
    call fcn 3

Parameters:
  Ag   :  DEPENDENT
  Bg   : [ -0.06378296878601784, 0. ]
  Cg   : [ 5.513146151675255, 0. ]
  Agp   : [ 0.16190517444163305, 0. ]
  Bgp   : [ -0.38929013881408153, 0. ]
  Cgp   : [ 25.0, 0. ]
  Auv  :  DEPENDENT
  Buv   : [ 0.8075541888080091, 0. ]
  Cuv   : [ 4.80045420160895, 0. ]
  Duv  : [    0     ]
  Euv   : [ 10.303987403046513, 0. ]
  Adv  :  DEPENDENT
  Bdv   : [ 1.0272474329808017, 0. ]
  Cdv   : [ 4.877548452916254, 0. ]
  Aubar: [ 0.0, 0.0 ]
  Bubar: [ 0.0, 0.0  ]
  Cubar   : [ 7.2454379936869096, 0. ]
  Dubar   : [ 1.6602549729030147, 0. ]
  Adbar   : [ 0.27491311449444417, 0. ]
  Bdbar   : [ -0.12563509414512022, 0. ]
  Cdbar   : [ 10.068758936839322, 0. ]

  ZERO : [ 0. ]
  fs : [ 0.4, 0.0 ]

Parameterisations:
  par_uv:
    class: HERAPDF
    parameters: [Auv,Buv,Cuv,Duv,Euv]
  par_dv:
    class: HERAPDF
    parameters: [Adv,Bdv,Cdv]
  par_ubar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cubar,Dubar]
  par_dbar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cdbar]
  par_s:
    class: Expression
    expression: "Adbar*fs/(1-fs)*(x^Bdbar*(1-x)^Cdbar)" 
  par_g:
    class: NegativeGluon
    parameters: [Ag,Bg,Cg,ZERO,ZERO,Agp,Bgp,Cgp]


DefaultDecomposition: proton
Decompositions:
  proton:
    class: UvDvUbarDbarS
    xuv: par_uv
    xdv: par_dv
    xubar: par_ubar
    xdbar: par_dbar
    xs: par_s
    xg: par_g

DefaultEvolution: proton-QCDNUM


Evolutions:
  proton-QCDNUM:
    ? !include evolutions/QCDNUM.yaml

Q0 : 1.378404875209
? !include constants.yaml
alphas : 0.118
byReaction:
  RT_DISNC:
    ? !include reactions/RT_DISNC.yaml
  FONLL_DISNC:
    ? !include reactions/FONLL_DISNC.yaml
  FONLL_DISCC:
    ? !include reactions/FONLL_DISCC.yaml
  FFABM_DISNC:
    ? !include reactions/FFABM_DISNC.yaml
  FFABM_DISCC:
    ? !include reactions/FFABM_DISCC.yaml
  AFB:
    ? !include reactions/AFB.yaml 
  APPLgrid:
    ? !include reactions/APPLgrid.yaml
  Fractal_DISNC:
    ? !include reactions/Fractal_DISNC.yaml


hf_scheme_DISNC :
  defaultValue : 'RT_DISNC' 
hf_scheme_DISCC :
  defaultValue : 'BaseDISCC' 

WriteLHAPDF6:
  name: "proton" 
  description: "..." 
  authors: "..." 
  reference: "..." 
  preferInternalGrid:
